### ISSUE TITLE
AlgaNode: invalid AlgaArg for parameter

### ISSUE THREAD

**Issue by geoffroymontel** [vitreo12/AlgaLib#80] opened 2022-03-14 21:52 UTC
Hello

Alga is quite fascinating !

Running Alga 1.1.1 on SC 3.12

I'm browsing the documentation and this AlgaArg example does not work 

```supercollider
(
Alga.boot({
    b = AlgaNode({ SinOsc.ar(100) });
    a = AlgaNode(
        { SinOsc.ar(\freq.kr(220) + \fm.ar) },
        [\fm, AlgaArg(b, scale: [-100, 100])]
    ).play(chans: 2);
});
)
```

brings

```ERROR: AlgaNode: invalid AlgaArg for parameter 'fm' ```

**Comment by geoffroymontel** [comment] 2022-03-14 21:55
Also

```supercollider
(
Alga.boot({
    b = AlgaNode({ SinOsc.ar(100) });
    c = AlgaNode({ Pulse.ar(100) });
    s.sync;
    a = AlgaPattern((
        def: { SinOsc.ar(\freq.kr(220) + \fm.ar) * EnvPerc.ar(release: 0.5) },
        dur: 0.5,
        fm: Pseq([
            AlgaArg(b, scale: [-100, 100]),
            AlgaArg(c, scale: [-200, 200])
        ], inf)
    )).play(chans: 2);
});
)
```

brings 

```WARNING: AlgaPattern: AlgaNode wasn't algaInstantiated yet. Using default value for fm```

**Comment by vitreo12** [comment] 2022-03-14 22:31
> ```supercollider
> (
> Alga.boot({
>     b = AlgaNode({ SinOsc.ar(100) });
>     a = AlgaNode(
>         { SinOsc.ar(\freq.kr(220) + \fm.ar) },
>         [\fm, AlgaArg(b, scale: [-100, 100])]
>     ).play(chans: 2);
> });
> )
> ```

Nice catch: I changed a few things for `AlgaArg` lately and forgot to patch in a few things. It's now fixed on develop.



> Also
> 
> ```supercollider
> (
> Alga.boot({
>     b = AlgaNode({ SinOsc.ar(100) });
>     c = AlgaNode({ Pulse.ar(100) });
>     s.sync;
>     a = AlgaPattern((
>         def: { SinOsc.ar(\freq.kr(220) + \fm.ar) * EnvPerc.ar(release: 0.5) },
>         dur: 0.5,
>         fm: Pseq([
>             AlgaArg(b, scale: [-100, 100]),
>             AlgaArg(c, scale: [-200, 200])
>         ], inf)
>     )).play(chans: 2);
> });
> )
> ```
> 
> brings
> 
> `WARNING: AlgaPattern: AlgaNode wasn't algaInstantiated yet. Using default value for fm`

I cannot reproduce this, but it should only execute once if it finds that one of the `AlgaNodes` has not been created on the server. Perhaps you have a high value for your `latency`? I'm using 0.3 and I receive no warnings.

**Comment by geoffroymontel** [comment] 2022-03-15 21:08
On my machine, `s.latency` is 0.2
I got it once then did not get it three times in a row. No big deal, don't worry !

**Comment by vitreo12** [comment] 2022-03-15 21:19
Good to hear, I'll close this then.

One other quick thing you can do is to use a `0.5.wait` call instead of the `s.sync`. That should give plenty of time for the two `AlgaNodes` to surely be instantiated on the server

**Closed** 2022-03-15 21:19 UTC

**Comment by geoffroymontel** [comment] 2022-03-15 21:26
Thanks !!
